# This file is auto-generated from the current state of the database.
# Run `bin/rails db:migrate` to generate this file after setting up your database.
# This file will be regenerated when you run migrations.

ActiveRecord::Schema[7.1].define(version: 2024_01_01_000007) do
  # These are extensions that must be enabled in order to support this database
  enable_extension "plpgsql"

  # Schema will be generated by migrations
end
